project:
  type: website
  output-dir: _site

website:
  title: ""
  # site-url: "https://ktvedt.github.io/sva-codelib/"
  navbar:
    left:
      - href: dashboard/index.qmd
        text: Dashboard

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

resources:
  - dashboard/projects.json

