project:
  type: website
  output-dir: docs

website:
  title: "sva-codelib"
  navbar:
    left:
      - href: dashboard/index.qmd
        text: Dashboard
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

resources:
  - dashboard/projects.json

