---
title: "Om kodebiblioteket"
---

Dette er et bibliotek med kode skrevet av forskere ved SVA: Senter for velferds- og arbeidslivsforskning på OsloMet. Her kan du finne kodesnutter som forskere ved SVA har delt, og som egner seg til gjenbruk i andre prosjekter. 

## Hvordan finner jeg kode?

Du finner kode på to måter:

* Søk med fritekst
    + Søkefunksjonen gir resultater som inneholder teksten du har skrevet inn. 
* Søk med filter i ulike kategorier, som metode og tema
    + Kategoriene oppdateres når du filtrerer, slik at bare relevante filtre er synlig. 
    + Deaktiver filtre ved å trykke igjen.

Du kan kombinere filter- og fritekstsøk. Trykk "Finn filer" for å se prosjektfilene på GitHub.

## Hvordan laster jeg ned kode?

Klikk på en kodefil på GitHub og velg "download raw file" (nedlastingsikon til høyre) for å laste ned filen lokalt. 

Er det flere filer må de lastes ned hver for seg. Pass på at du har samme mappestruktur som filene har i GitHub.

**Kreditering**: Vi oppfordrer til å kreditere forfatterne når det gir mening, og du bruker store deler av andres kode.

---

## Hvordan kan jeg bidra?

Du må ha en GitHub-konto tilknyttet SVA for å sende inn kode. Send inn en pull request på GitHub eller kontakt administrator: [navn + kodebibliotek@365.oslomet.no](mailto:kodebibliotek@365.oslomet.no).

**Kan jeg foreslå nye funksjoner?**

Ja, vi setter pris på forslag og tilbakemeldinger! Bruk issues på GitHub eller kontakt administrator: [navn + kodebibliotek@365.oslomet.no](mailto:kodebibliotek@365.oslomet.no).