name: Build metadata index

on:
  push:
    branches:
        - main

jobs:
  build-metadata:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install python dependencies
        run: pip install pyyaml pandas openpyxl pathspec

      - name: Generate projects.json
        run: python generate_projects_json.py

      - name: Commit updated metadata
        run: |
          if git diff --quiet; then
            echo "No metadata changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dashboard/projects.json projects
          git status --short
          git commit -m "chore: auto-refresh project metadata"
          git push

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
