name: Build metadata index

on:
  push:
    paths:
      - "projects/**"
      - "generate_projects_json.py"

jobs:
  build-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate projects.json
        run: python generate_projects_json.py

      - name: Commit and push projects.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dashboard/projects.json || true
          git diff --cached --quiet || git commit -m "Update projects.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ktvedt/sva-codelib.git